name: Run Unit Tests and Lint Files
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Lint files and run type-checks
        run: npm run lint
